server:
  port: 8097
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100
spring:
  messages:
    basename: i18n/messages
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

bitter:
  sqlLog: true
  cache:
    enabledRedis: true
    enabledLocalCache: false
    redis:
      host: 192.168.1.3
      port: 6379
      database: 1
      password:
      timeout: 100
      lettuce:
        pool:
          minIdle: 0
          maxIdle: 10
          maxActive: 30
          maxTotal: 30
          maxWait: 200

mybatis-plus:
  typeAliasesPackage: io.github.davidchild.bitter.**.domain
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml


